### PR TITLE
Change the str representation of AppHookConfig

### PR DESCRIPTION
**Pull request by yakky**
by using the related CMSApp name instead of the type

### CODE REVIEW

**Comment by yakky** [comment]
@stefanfoulis @intellectronica @mkoistinen 

This assumes that a 1:1 mapping exists between CMSApp and AppHookConfig (which is not true, actually)
Is config model sharing between apphooks sensible?

**Comment by mkoistinen** [comment]
LGTM

I'm not sure I understand the concern about the possible 1:1 mapping issue. This PR improves the code as it stands.

**Comment by yakky** [comment]
No issue, except the fact that now this is not enforced in any way :)
Currently you can have two CMSApp which shares the same model (like in the code below), and this breaks  the code of this PR:

    class App1(CMSConfigApp):
         ....
         app_config = ConfigModel1

    class App2(CMSConfigApp):
         ....
         app_config = ConfigModel1

If we decide that CMSApp and AppHookConfig must have a One-to-One relation I'll change the code to enforce this

**Comment by yakky** [comment]
1:1 relationship ensured in latest ``future/integration`` branch.
Merging this

**Pull request merged**
