### PR TITLE
Fix build_attrs django 1.11 compatibility

### PR DESCRIPTION
**Pull request by Angoreher**

### CODE REVIEW

**Comment by adrien-delhorme** [comment]
Is there someone around here with write access to this repository, to merge this pull request?

**Comment by yakky** [comment]
@Angoreher unfortunately this is not enough to gain Django 1.11 support. We have a larger patch in the works, but we first need to fix dependencies
Hopefully it's not too far away

**Comment by Angoreher** [comment]
Ack. Thank you very much.

**Comment by Angoreher** [comment]
Should I close this pull request?

**Comment by yakky** [comment]
@Angoreher thanks again for contributing this. Your PR has been incorporated in #54 and merged.
Expect a release soon

**Pull request closed without merging**
