### PR TITLE
updates widget rendering for Django >=1.11

### PR DESCRIPTION
**Pull request by SteinRobert**
Updates rendering of apphook config select widget for Django>=1.11

Even though this might not be a complete update to Django >=1.11 it might help to update the project :)

### CODE REVIEW

**Comment by yakky** [comment]
Thanks @SteinRobert ! we have some rough drafts for 1.11 (we need django-appdata to be updated first), but this will definitely help!

**Comment by yakky** [comment]
A rendering  compatible with Django < 1.11 will be needed, but I guess we have no other ooption than duplicating the code here (we will drop <1.11 in the near future ayway, so it doesn't have to live for long here)

**Comment by SteinRobert** [comment]
Sure that's fine. Glad if it helps :)

**Comment by yakky** [comment]
@SteinRobert thanks again for contributing this. Your PR has been incorporated in #54 and merged.
Expect a release soon

**Pull request closed without merging**
