### PR TITLE
Get apphook config from obj + cache apphook config field lookup

### PR DESCRIPTION
**Pull request by Chive**
Caches apphook config field names on model/class and adds a helper function to get all apphook configs from an object directly

### CODE REVIEW

**Comment by chronossc** [comment]
:+1:

**Comment by mkoistinen** [comment]
Nicely done, @Chive! :+1:

**Comment by Chive** [comment]
I think there's an issue with this though, esp. with the caching. I experience the following when running the test suite (currently extending it):

```python
Python 2.7.9 (default, May  1 2015, 19:04:44)
[GCC 4.2.1 Compatible Apple LLVM 6.1.0 (clang-602.0.49)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
(InteractiveConsole)
>>> from aldryn_apphooks_config.tests.utils.example.models import Article, News
>>> from aldryn_apphooks_config.utils import get_apphook_field_names
>>> get_apphook_field_names(Article)
['section']
>>> get_apphook_field_names(News)
['section']
>>> exit()

Python 2.7.9 (default, May  1 2015, 19:04:44)
[GCC 4.2.1 Compatible Apple LLVM 6.1.0 (clang-602.0.49)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
(InteractiveConsole)
>>> from aldryn_apphooks_config.tests.utils.example.models import Article, News
>>> from aldryn_apphooks_config.utils import get_apphook_field_names
>>> get_apphook_field_names(News)
['section', 'config']
>>> get_apphook_field_names(Article)
['section']
>>> get_apphook_field_names(News)
['section', 'config']
>>>
```

Note that ``Article`` is the parent class of ``News`` (https://github.com/aldryn/aldryn-apphooks-config/blob/master/aldryn_apphooks_config/tests/utils/example/models.py). So it seems that the parent class is actually caching the fields for the children as well :(

**Comment by Chive** [comment]
Fixed the issue mentioned in the previous comment by using app&model specific caching keys on the objects ``APP_CONFIG_FIELDS_KEY = '_app_config_field_names_{app_label}.{model_name}'``

**Comment by Chive** [comment]
despite coverage decreasing by lousy 0.43% (see [``aldryn_apphooks_config/tests/test_config.py#L388-L397``](https://github.com/aldryn/aldryn-apphooks-config/blob/feature/get-apphook-config-from-obj/aldryn_apphooks_config/tests/test_config.py#L388-L397)) - ready for check in. I'll rebase & squash into one commit before merge.

**Comment by GaretJax** [comment]
LGTM :star2:

**Comment by jmelett** [comment]
LGTM

**Pull request closed without merging**
