### PR TITLE
Adds unique constraint

### PR DESCRIPTION
**Pull request by mkoistinen**
Addresses #17

### CODE REVIEW

**Comment by intellectronica** [comment]
:+1:

**Comment by yakky** [comment]
:+1:

**Comment by yakky** [comment]
Django 1.5 is not supported, dropping from the test matrix

**Comment by yakky** [comment]
Migrations missing

**Comment by mkoistinen** [comment]
Rebased, added null=True too.

**Comment by mkoistinen** [comment]
@yakky This project has no migrations, perhaps these should be in a separate commit?

**Comment by mkoistinen** [comment]
@yakky, this project has no migrations.

**Comment by yakky** [comment]
@mkoistinen I'm a moron :) No migrations needed here: models are abstract! ;)

**Pull request merged**
